### ISSUE TITLE
Infografía Realidad Aumentada #1

### ISSUE THREAD

**Issue by claudiasilvavenda** [SistemasTecTlaxiaco/infografia-claudiasilvavenda#1]
[Infografia_CLAUDIA.SILVA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-claudiasilvavenda/files/8126716/Infografia_CLAUDIA.SILVA.pdf)

**Comment by JulioCesar69** [comment]
Bien realizado
Calificación 18%.
Nota: Las fuentes de las gráficas prestadas no están citadas

**Comment by josealfredo79** [comment]
Bien hecho y revisado
